version: '3.9'

services:

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  db-dev-1:
    image: postgres:14.5
    container_name: db-dev-1
    command: postgres -c 'max_connections=500'
    ports:
      - "9072:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password1
      - POSTGRES_USER=user1
      - POSTGRES_DB=db1
#    networks:
#      spring-postgre-docker-network-1:

# jdbc:postgresql://localhost:9072/db1?user=user1&password=password1

# sudo docker compose -f docker-compose-postgre.yml down
# sudo docker compose -f docker-compose-postgre.yml up -d